server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.253.128:9200
  thymeleaf:
    cache: false
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.253.128
    virtual-host: /fengge
    username: fengge
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 6
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
